# config.yaml

websites_base_path: "./test_env/sites"
temp_extract_path: "./test_env/tmp/temp_extract"

projects:
  - repo: "bowling-score-api-ts"
    owner: "hamilton-marc"
    name: "Bowling Score API"
    workflow_filename: "build_deployment_artifact.yml"
    artifact_filename: "release.7z"
    download_directory: "./test_env/artifacts/bowling-score-api-ts"
    websites:
      - "bowlingapi-dev.unionhills.dev"
      - "bowlingapi-qa.unionhills.dev"
      - "bowlingapi-staging.unionhills.dev"
      - "bowlingapi.unionhills.dev"
    allowed_branches:
      - "main"
    preserve_regex: "^Web\\.config$"
