# config.yaml

websites_base_path: "work/sites"
temp_extract_path: "work/tmp/temp_extract"

github_config:
  base_url: "https://api.github.com"
  owner: "hamilton-marc"

projects:
  - repo: "bowling-score-api-ts"
    name: "Bowling Score API"
    workflow_filename: "bowling-score-ci-cd.yml"
    download_directory: "work/artifacts/bowling-score-api-ts"
    websites:
      - "bowlingapi-dev.unionhills.dev"
      - "bowlingapi-qa.unionhills.dev"
      - "bowlingapi-staging.unionhills.dev"
      - "bowlingapi.unionhills.dev"
    allowed_branches:
      - "main"
    preserve_regex: "^Web\\.config$"
